### ISSUE TITLE
Roadmap for v1

### ISSUE THREAD

**Issue by jameslnewell** [jameslnewell/tradie#18]
What I want implemented for v1:

- [x] fingerprinting for cache busting assets including *.js and *.css files and files referenced from HTML/JSX e.g. image and video paths
- [ ] linting config per env e.g. user can allow `console.log` in dev environment but not in prod
- [x] allow plugins to block exit and cause failure exit codes (maybe use .before() and .after() middleware like go-fetch, maybe with promises instead of node async style)
- [ ] logging util for built-in commands and plugins to use which takes into account --verbose for all commands 
- [ ] validation of the config file properties?
- [ ] improved test coverage
- [ ] improved documentation
- [ ] image optimisation? built in as best practice or supported using a plugin?
- [ ] code coverage plugin
- [ ] fix outstanding bugs

Features:
- [ ] #29  
- [ ] #28 
- [ ] #27  
- [ ] #26  
- [ ] #25 
- [ ] #21
- [ ] #19 
- [ ] #7 
- [ ] #5

Bugs:
- [ ] #23
- [ ] #12
- [ ] #11
- [ ] #10 
- [ ] #32 
- [ ] #34
